"""Report foundation, draft Word export, and report QA helpers."""

from concrete_pmm_pro.reporting.readiness import (
    ReportReadinessItem,
    ReportReadinessSummary,
    check_report_readiness,
    report_readiness_to_dataframe,
)
from concrete_pmm_pro.reporting.report_manifest import (
    ReportManifest,
    build_report_manifest,
    generate_plain_text_report_outline,
    report_manifest_to_json_dict,
    report_manifest_to_summary_dataframe,
)
from concrete_pmm_pro.reporting.figure_export import plotly_figure_to_html_bytes, plotly_figure_to_png_bytes
from concrete_pmm_pro.reporting.word_export import (
    ReportExportOptions,
    add_draft_disclaimer,
    add_limitations_section,
    add_page_break,
    add_key_value_table,
    add_report_heading,
    add_report_footer_note,
    add_terminology_section,
    add_unit_conventions_section,
    add_warning_box_or_section,
    apply_document_defaults,
    apply_heading_styles,
    build_draft_word_report,
    dataframe_to_word_table,
    save_draft_word_report,
    set_table_style,
)
from concrete_pmm_pro.reporting.report_qa import (
    ReportQAItem,
    ReportQASummary,
    extract_docx_headings,
    extract_docx_text,
    report_qa_summary_to_dataframe,
    run_word_report_qa,
    validate_draft_disclaimer,
    validate_engineering_limitations_present,
    validate_engineering_warnings_present,
    validate_no_misleading_certification_language,
    validate_report_tables_and_figures_present,
    validate_required_report_headings,
    validate_terminology_present,
    validate_traceability_and_readiness_present,
    validate_unit_conventions_present,
)
from concrete_pmm_pro.reporting.report_models import (
    ReportMetadata,
    ReportSection,
    ReportTableInfo,
    default_report_metadata,
)
from concrete_pmm_pro.reporting.report_figures import (
    ReportFigureContext,
    ReportFigureExportItem,
    build_exportable_figure,
    build_report_figure_context,
    collect_report_figure_export_items,
    report_figure_export_items_to_dataframe,
    safe_report_figure_filename,
)
from concrete_pmm_pro.reporting.report_sections import default_report_section_plan, report_sections_to_dataframe
from concrete_pmm_pro.reporting.report_tables import collect_available_report_tables, report_tables_to_dataframe
from concrete_pmm_pro.reporting.limitations import (
    EngineeringLimitation,
    collect_limitations_for_report,
    deduplicate_limitations_by_key,
    engineering_limitations_to_dataframe,
    get_engineering_limitations,
)
from concrete_pmm_pro.reporting.terminology import EngineeringTerm, get_standard_terminology, terminology_to_dataframe
from concrete_pmm_pro.reporting.traceability import (
    ReportFigureInfo,
    ResultTraceabilitySnapshot,
    build_result_traceability_snapshot,
    collect_available_report_figures,
    collect_engineering_warnings,
    deduplicate_preserve_order,
    report_figures_to_dataframe,
    result_traceability_snapshot_to_dataframe,
)
from concrete_pmm_pro.reporting.units import UnitConvention, get_unit_conventions, unit_conventions_to_dataframe

__all__ = [
    "EngineeringTerm",
    "EngineeringLimitation",
    "ReportFigureInfo",
    "ReportFigureContext",
    "ReportFigureExportItem",
    "ReportExportOptions",
    "ReportManifest",
    "ReportMetadata",
    "ReportQAItem",
    "ReportQASummary",
    "ReportReadinessItem",
    "ReportReadinessSummary",
    "ReportSection",
    "ReportTableInfo",
    "ResultTraceabilitySnapshot",
    "UnitConvention",
    "build_result_traceability_snapshot",
    "build_report_manifest",
    "build_exportable_figure",
    "build_report_figure_context",
    "build_draft_word_report",
    "check_report_readiness",
    "collect_available_report_figures",
    "collect_available_report_tables",
    "collect_engineering_warnings",
    "collect_limitations_for_report",
    "collect_report_figure_export_items",
    "default_report_metadata",
    "default_report_section_plan",
    "dataframe_to_word_table",
    "deduplicate_preserve_order",
    "deduplicate_limitations_by_key",
    "engineering_limitations_to_dataframe",
    "extract_docx_headings",
    "extract_docx_text",
    "generate_plain_text_report_outline",
    "get_standard_terminology",
    "get_engineering_limitations",
    "get_unit_conventions",
    "report_figures_to_dataframe",
    "report_figure_export_items_to_dataframe",
    "report_manifest_to_json_dict",
    "report_manifest_to_summary_dataframe",
    "report_qa_summary_to_dataframe",
    "report_readiness_to_dataframe",
    "report_sections_to_dataframe",
    "report_tables_to_dataframe",
    "plotly_figure_to_html_bytes",
    "plotly_figure_to_png_bytes",
    "run_word_report_qa",
    "save_draft_word_report",
    "add_limitations_section",
    "add_draft_disclaimer",
    "add_key_value_table",
    "add_page_break",
    "add_report_heading",
    "add_report_footer_note",
    "add_terminology_section",
    "add_unit_conventions_section",
    "add_warning_box_or_section",
    "apply_document_defaults",
    "apply_heading_styles",
    "set_table_style",
    "result_traceability_snapshot_to_dataframe",
    "terminology_to_dataframe",
    "unit_conventions_to_dataframe",
    "safe_report_figure_filename",
    "validate_draft_disclaimer",
    "validate_engineering_limitations_present",
    "validate_engineering_warnings_present",
    "validate_no_misleading_certification_language",
    "validate_report_tables_and_figures_present",
    "validate_required_report_headings",
    "validate_terminology_present",
    "validate_traceability_and_readiness_present",
    "validate_unit_conventions_present",
]
